# Generated by Django 4.1.7 on 2023-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
