# Generated by Django 4.1.7 on 2023-03-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('sucursales', '0003_sucursales_empresa'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_empresa', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='sucursal',
            field=models.ManyToManyField(to='sucursales.sucursales'),
        ),
    ]
