# Generated by Django 4.1.7 on 2023-03-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulos_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='receta',
            field=models.TextField(default=''),
        ),
    ]
