# Generated by Django 4.1.7 on 2023-03-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulos_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='menu',
            field=models.BooleanField(default=True),
        ),
    ]
