# Generated by Django 4.1.7 on 2023-03-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0006_alter_sucursales_imagen'),
        ('articulos', '0004_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='sucursal',
            field=models.ManyToManyField(blank=True, to='sucursales.sucursales'),
        ),
    ]
