# Generated by Django 4.1.7 on 2023-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
