# Generated by Django 4.1.7 on 2023-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_sucursales_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
