# Generated by Django 4.1.7 on 2023-03-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_sucursales_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rubros'),
        ),
    ]
