# Generated by Django 4.1.7 on 2023-03-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0005_sucursales_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales'),
        ),
    ]
