# Generated by Django 4.1.7 on 2023-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rubros'),
        ),
    ]
