# Generated by Django 4.1.7 on 2023-03-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('rubros', '0002_rubros_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubros',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_empresa', to='empresa.empresa'),
        ),
    ]
