# Generated by Django 4.1.7 on 2023-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubros', '0003_rubros_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubros',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
