# Generated by Django 4.1.7 on 2023-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubros', '0004_rubros_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubros',
            name='menu',
            field=models.BooleanField(default=True),
        ),
    ]
