# Generated by Django 4.1.7 on 2023-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.TextField(blank=True, default='', max_length=13),
        ),
    ]
