# Generated by Django 4.1.7 on 2023-03-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
